---
- name: Deploy App
  hosts: app
#  tags: deploy-tag
  become: true

  tasks:
    - name: Fetch the latest version off application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/appuser/reddit
        version: monolith
      notify: reload puma

    - name:
      bundler:
        state: present
        chdir: /home/appuser/reddit
      tags: deploy-tag

  handlers:
    - name: reload puma
      systemd: name=puma state=restarted
